# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/networking/requests/item/stock/GetStockInfoRequest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/networking/requests/item/stock/GetStockInfoRequest.proto',
  package='TeamsonUK.Usability.Networking.Requests.Item.Stock',
  syntax='proto3',
  serialized_options=b'\n6uk.co.teamson.usability.networking.requests.item.stockP\001\312\0022TeamsonUK\\Usability\\Networking\\Requests\\Item\\Stock',
  serialized_pb=b'\n;uk/networking/requests/item/stock/GetStockInfoRequest.proto\x12\x32TeamsonUK.Usability.Networking.Requests.Item.Stock\"\xf1\x06\n\x13GetStockInfoRequest\x12\x18\n\x10include_inactive\x18\x01 \x01(\x08\x12\x18\n\x10\x62usiness_partner\x18\x02 \x01(\t\x12i\n\x0cpricing_mode\x18\x03 \x01(\x0e\x32S.TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.PricingMode\x12\x1c\n\x14specified_price_list\x18\x04 \x01(\t\x12\x65\n\nitem_scope\x18\x05 \x01(\x0e\x32Q.TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.ItemScope\x12\x17\n\x0fspecified_items\x18\x06 \x03(\t\x12\x1c\n\x14specified_warehouses\x18\x07 \x03(\t\x12g\n\x0b\x62om_handler\x18\x08 \x01(\x0e\x32R.TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.BOMHandler\x12\x15\n\rbom_warehouse\x18\t \x01(\t\x12\x13\n\x0bheight_unit\x18\n \x01(\t\x12\x13\n\x0bweight_unit\x18\x0b \x01(\t\x12\x13\n\x0blength_unit\x18\x0c \x01(\t\x12\x12\n\nwidth_unit\x18\r \x01(\t\x12\x19\n\x11get_delivery_info\x18\x0e \x01(\x08\x12\x18\n\x10get_pricing_info\x18\x0f \x01(\x08\"E\n\x0bPricingMode\x12\x0e\n\nNO_PRICING\x10\x00\x12\x0c\n\x08\x42P_PRICE\x10\x01\x12\x18\n\x14SPECIFIED_PRICE_LIST\x10\x02\"]\n\tItemScope\x12\r\n\tALL_ITEMS\x10\x00\x12\x14\n\x10\x42P_CATALOG_ITEMS\x10\x01\x12\x16\n\x12\x42P_PRICELIST_ITEMS\x10\x02\x12\x13\n\x0fSPECIFIED_ITEMS\x10\x03\"Q\n\nBOMHandler\x12\x0e\n\nIGNORE_BOM\x10\x00\x12\x1b\n\x17\x42Y_INDIVIDUAL_WAREHOUSE\x10\x01\x12\x16\n\x12SPECIFIC_WAREHOUSE\x10\x02\x42o\n6uk.co.teamson.usability.networking.requests.item.stockP\x01\xca\x02\x32TeamsonUK\\Usability\\Networking\\Requests\\Item\\Stockb\x06proto3'
)



_GETSTOCKINFOREQUEST_PRICINGMODE = _descriptor.EnumDescriptor(
  name='PricingMode',
  full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.PricingMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_PRICING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BP_PRICE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIFIED_PRICE_LIST', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=750,
  serialized_end=819,
)
_sym_db.RegisterEnumDescriptor(_GETSTOCKINFOREQUEST_PRICINGMODE)

_GETSTOCKINFOREQUEST_ITEMSCOPE = _descriptor.EnumDescriptor(
  name='ItemScope',
  full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.ItemScope',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL_ITEMS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BP_CATALOG_ITEMS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BP_PRICELIST_ITEMS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIFIED_ITEMS', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=821,
  serialized_end=914,
)
_sym_db.RegisterEnumDescriptor(_GETSTOCKINFOREQUEST_ITEMSCOPE)

_GETSTOCKINFOREQUEST_BOMHANDLER = _descriptor.EnumDescriptor(
  name='BOMHandler',
  full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.BOMHandler',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IGNORE_BOM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BY_INDIVIDUAL_WAREHOUSE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIFIC_WAREHOUSE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=916,
  serialized_end=997,
)
_sym_db.RegisterEnumDescriptor(_GETSTOCKINFOREQUEST_BOMHANDLER)


_GETSTOCKINFOREQUEST = _descriptor.Descriptor(
  name='GetStockInfoRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='include_inactive', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.include_inactive', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='business_partner', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.business_partner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pricing_mode', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.pricing_mode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_price_list', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.specified_price_list', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_scope', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.item_scope', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_items', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.specified_items', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_warehouses', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.specified_warehouses', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bom_handler', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.bom_handler', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bom_warehouse', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.bom_warehouse', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height_unit', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.height_unit', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight_unit', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.weight_unit', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_unit', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.length_unit', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width_unit', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.width_unit', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_delivery_info', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.get_delivery_info', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_pricing_info', full_name='TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest.get_pricing_info', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETSTOCKINFOREQUEST_PRICINGMODE,
    _GETSTOCKINFOREQUEST_ITEMSCOPE,
    _GETSTOCKINFOREQUEST_BOMHANDLER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=997,
)

_GETSTOCKINFOREQUEST.fields_by_name['pricing_mode'].enum_type = _GETSTOCKINFOREQUEST_PRICINGMODE
_GETSTOCKINFOREQUEST.fields_by_name['item_scope'].enum_type = _GETSTOCKINFOREQUEST_ITEMSCOPE
_GETSTOCKINFOREQUEST.fields_by_name['bom_handler'].enum_type = _GETSTOCKINFOREQUEST_BOMHANDLER
_GETSTOCKINFOREQUEST_PRICINGMODE.containing_type = _GETSTOCKINFOREQUEST
_GETSTOCKINFOREQUEST_ITEMSCOPE.containing_type = _GETSTOCKINFOREQUEST
_GETSTOCKINFOREQUEST_BOMHANDLER.containing_type = _GETSTOCKINFOREQUEST
DESCRIPTOR.message_types_by_name['GetStockInfoRequest'] = _GETSTOCKINFOREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetStockInfoRequest = _reflection.GeneratedProtocolMessageType('GetStockInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTOCKINFOREQUEST,
  '__module__' : 'uk.networking.requests.item.stock.GetStockInfoRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.Item.Stock.GetStockInfoRequest)
  })
_sym_db.RegisterMessage(GetStockInfoRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
