# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/networking/responses/ar/sales_order/InsertBasicSalesOrderResponse.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/networking/responses/ar/sales_order/InsertBasicSalesOrderResponse.proto',
  package='TeamsonUK.Usability.Networking.Responses.AR.SalesOrder',
  syntax='proto3',
  serialized_options=b'\n:uk.co.teamson.usability.networking.responses.ar.salesorderP\001\312\0026TeamsonUK\\Usability\\Networking\\Responses\\AR\\SalesOrder',
  serialized_pb=b'\nJuk/networking/responses/ar/sales_order/InsertBasicSalesOrderResponse.proto\x12\x36TeamsonUK.Usability.Networking.Responses.AR.SalesOrder\"\x1f\n\x1dInsertBasicSalesOrderResponseBw\n:uk.co.teamson.usability.networking.responses.ar.salesorderP\x01\xca\x02\x36TeamsonUK\\Usability\\Networking\\Responses\\AR\\SalesOrderb\x06proto3'
)




_INSERTBASICSALESORDERRESPONSE = _descriptor.Descriptor(
  name='InsertBasicSalesOrderResponse',
  full_name='TeamsonUK.Usability.Networking.Responses.AR.SalesOrder.InsertBasicSalesOrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['InsertBasicSalesOrderResponse'] = _INSERTBASICSALESORDERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InsertBasicSalesOrderResponse = _reflection.GeneratedProtocolMessageType('InsertBasicSalesOrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSERTBASICSALESORDERRESPONSE,
  '__module__' : 'uk.networking.responses.ar.sales_order.InsertBasicSalesOrderResponse_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Responses.AR.SalesOrder.InsertBasicSalesOrderResponse)
  })
_sym_db.RegisterMessage(InsertBasicSalesOrderResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
