# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/data/item/stock/ChildItemStock.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from uk.data.item.stock import StockDeliveryInfo_pb2 as uk_dot_data_dot_item_dot_stock_dot_StockDeliveryInfo__pb2
from uk.data.item.stock import WarehouseStock_pb2 as uk_dot_data_dot_item_dot_stock_dot_WarehouseStock__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/data/item/stock/ChildItemStock.proto',
  package='TeamsonUK.Usability.Data.Item.Stock',
  syntax='proto3',
  serialized_options=b'\n\'uk.co.teamson.usability.data.item.stockP\001\312\002#TeamsonUK\\Usability\\Data\\Item\\Stock',
  serialized_pb=b'\n\'uk/data/item/stock/ChildItemStock.proto\x12#TeamsonUK.Usability.Data.Item.Stock\x1a*uk/data/item/stock/StockDeliveryInfo.proto\x1a\'uk/data/item/stock/WarehouseStock.proto\"\x9e\x04\n\x0e\x43hildItemStock\x12\x11\n\titem_code\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0csales_height\x18\x03 \x01(\x01\x12\x13\n\x0bheight_unit\x18\x04 \x01(\t\x12\x14\n\x0csales_weight\x18\x05 \x01(\x01\x12\x13\n\x0bweight_unit\x18\x06 \x01(\t\x12\x14\n\x0csales_length\x18\x07 \x01(\x01\x12\x13\n\x0blength_unit\x18\x08 \x01(\t\x12\x13\n\x0bsales_width\x18\t \x01(\x01\x12\x12\n\nwidth_unit\x18\n \x01(\t\x12\x13\n\x0bis_on_order\x18\x0b \x01(\x08\x12\x10\n\x08quantity\x18\x0c \x01(\x01\x12\x13\n\x0btotal_stock\x18\r \x01(\x05\x12\x11\n\tis_active\x18\x0e \x01(\x08\x12M\n\rnext_delivery\x18\x0f \x01(\x0b\x32\x36.TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfo\x12N\n\x0e\x61ll_deliveries\x18\x10 \x03(\x0b\x32\x36.TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfo\x12L\n\x0fwarehouse_stock\x18\x11 \x03(\x0b\x32\x33.TeamsonUK.Usability.Data.Item.Stock.WarehouseStockBQ\n\'uk.co.teamson.usability.data.item.stockP\x01\xca\x02#TeamsonUK\\Usability\\Data\\Item\\Stockb\x06proto3'
  ,
  dependencies=[uk_dot_data_dot_item_dot_stock_dot_StockDeliveryInfo__pb2.DESCRIPTOR,uk_dot_data_dot_item_dot_stock_dot_WarehouseStock__pb2.DESCRIPTOR,])




_CHILDITEMSTOCK = _descriptor.Descriptor(
  name='ChildItemStock',
  full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_code', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.item_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sales_height', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.sales_height', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height_unit', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.height_unit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sales_weight', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.sales_weight', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight_unit', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.weight_unit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sales_length', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.sales_length', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_unit', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.length_unit', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sales_width', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.sales_width', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width_unit', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.width_unit', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_on_order', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.is_on_order', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.quantity', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_stock', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.total_stock', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_active', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.is_active', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_delivery', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.next_delivery', index=14,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all_deliveries', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.all_deliveries', index=15,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_stock', full_name='TeamsonUK.Usability.Data.Item.Stock.ChildItemStock.warehouse_stock', index=16,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=708,
)

_CHILDITEMSTOCK.fields_by_name['next_delivery'].message_type = uk_dot_data_dot_item_dot_stock_dot_StockDeliveryInfo__pb2._STOCKDELIVERYINFO
_CHILDITEMSTOCK.fields_by_name['all_deliveries'].message_type = uk_dot_data_dot_item_dot_stock_dot_StockDeliveryInfo__pb2._STOCKDELIVERYINFO
_CHILDITEMSTOCK.fields_by_name['warehouse_stock'].message_type = uk_dot_data_dot_item_dot_stock_dot_WarehouseStock__pb2._WAREHOUSESTOCK
DESCRIPTOR.message_types_by_name['ChildItemStock'] = _CHILDITEMSTOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChildItemStock = _reflection.GeneratedProtocolMessageType('ChildItemStock', (_message.Message,), {
  'DESCRIPTOR' : _CHILDITEMSTOCK,
  '__module__' : 'uk.data.item.stock.ChildItemStock_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Data.Item.Stock.ChildItemStock)
  })
_sym_db.RegisterMessage(ChildItemStock)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
