# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/data/item/stock/ItemStock.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from uk.data.item.stock import ChildItemStock_pb2 as uk_dot_data_dot_item_dot_stock_dot_ChildItemStock__pb2
from uk.data.item.stock import WarehouseStock_pb2 as uk_dot_data_dot_item_dot_stock_dot_WarehouseStock__pb2
from uk.data.item.stock import StockDeliveryInfo_pb2 as uk_dot_data_dot_item_dot_stock_dot_StockDeliveryInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/data/item/stock/ItemStock.proto',
  package='TeamsonUK.Usability.Data.Item.Stock',
  syntax='proto3',
  serialized_options=b'\n\'uk.co.teamson.usability.data.item.stockP\001\312\002#TeamsonUK\\Usability\\Data\\Item\\Stock',
  serialized_pb=b'\n\"uk/data/item/stock/ItemStock.proto\x12#TeamsonUK.Usability.Data.Item.Stock\x1a\'uk/data/item/stock/ChildItemStock.proto\x1a\'uk/data/item/stock/WarehouseStock.proto\x1a*uk/data/item/stock/StockDeliveryInfo.proto\"\xd0\x05\n\tItemStock\x12\x11\n\titem_code\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0csales_height\x18\x03 \x01(\x01\x12\x13\n\x0bheight_unit\x18\x04 \x01(\t\x12\x14\n\x0csales_weight\x18\x05 \x01(\x01\x12\x13\n\x0bweight_unit\x18\x06 \x01(\t\x12\x14\n\x0csales_length\x18\x07 \x01(\x01\x12\x13\n\x0blength_unit\x18\x08 \x01(\t\x12\x13\n\x0bsales_width\x18\t \x01(\x01\x12\x12\n\nwidth_unit\x18\n \x01(\t\x12\x14\n\x0cis_component\x18\x0b \x01(\x08\x12\x13\n\x0bis_on_order\x18\x0c \x01(\x08\x12\x0f\n\x07\x62\x61rcode\x18\r \x01(\t\x12\x16\n\x0e\x63\x61talog_number\x18\x0e \x01(\t\x12\x13\n\x0btotal_stock\x18\x0f \x01(\x05\x12\x11\n\tis_active\x18\x10 \x01(\x08\x12\x11\n\tsales_uom\x18\x11 \x01(\t\x12\x12\n\nunit_price\x18\x12 \x01(\t\x12\x17\n\x0f\x65\x66\x66\x65\x63tive_price\x18\x13 \x01(\t\x12M\n\rnext_delivery\x18\x14 \x01(\x0b\x32\x36.TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfo\x12H\n\x0b\x63hild_items\x18\x15 \x03(\x0b\x32\x33.TeamsonUK.Usability.Data.Item.Stock.ChildItemStock\x12L\n\x0fwarehouse_stock\x18\x16 \x03(\x0b\x32\x33.TeamsonUK.Usability.Data.Item.Stock.WarehouseStock\x12N\n\x0e\x61ll_deliveries\x18\x17 \x03(\x0b\x32\x36.TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfoBQ\n\'uk.co.teamson.usability.data.item.stockP\x01\xca\x02#TeamsonUK\\Usability\\Data\\Item\\Stockb\x06proto3'
  ,
  dependencies=[uk_dot_data_dot_item_dot_stock_dot_ChildItemStock__pb2.DESCRIPTOR,uk_dot_data_dot_item_dot_stock_dot_WarehouseStock__pb2.DESCRIPTOR,uk_dot_data_dot_item_dot_stock_dot_StockDeliveryInfo__pb2.DESCRIPTOR,])




_ITEMSTOCK = _descriptor.Descriptor(
  name='ItemStock',
  full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_code', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.item_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sales_height', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.sales_height', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height_unit', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.height_unit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sales_weight', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.sales_weight', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight_unit', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.weight_unit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sales_length', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.sales_length', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_unit', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.length_unit', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sales_width', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.sales_width', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width_unit', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.width_unit', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_component', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.is_component', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_on_order', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.is_on_order', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='barcode', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.barcode', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='catalog_number', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.catalog_number', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_stock', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.total_stock', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_active', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.is_active', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sales_uom', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.sales_uom', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit_price', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.unit_price', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='effective_price', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.effective_price', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_delivery', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.next_delivery', index=19,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='child_items', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.child_items', index=20,
      number=21, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_stock', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.warehouse_stock', index=21,
      number=22, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all_deliveries', full_name='TeamsonUK.Usability.Data.Item.Stock.ItemStock.all_deliveries', index=22,
      number=23, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=922,
)

_ITEMSTOCK.fields_by_name['next_delivery'].message_type = uk_dot_data_dot_item_dot_stock_dot_StockDeliveryInfo__pb2._STOCKDELIVERYINFO
_ITEMSTOCK.fields_by_name['child_items'].message_type = uk_dot_data_dot_item_dot_stock_dot_ChildItemStock__pb2._CHILDITEMSTOCK
_ITEMSTOCK.fields_by_name['warehouse_stock'].message_type = uk_dot_data_dot_item_dot_stock_dot_WarehouseStock__pb2._WAREHOUSESTOCK
_ITEMSTOCK.fields_by_name['all_deliveries'].message_type = uk_dot_data_dot_item_dot_stock_dot_StockDeliveryInfo__pb2._STOCKDELIVERYINFO
DESCRIPTOR.message_types_by_name['ItemStock'] = _ITEMSTOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemStock = _reflection.GeneratedProtocolMessageType('ItemStock', (_message.Message,), {
  'DESCRIPTOR' : _ITEMSTOCK,
  '__module__' : 'uk.data.item.stock.ItemStock_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Data.Item.Stock.ItemStock)
  })
_sym_db.RegisterMessage(ItemStock)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
