# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/data/item/stock/StockDeliveryInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/data/item/stock/StockDeliveryInfo.proto',
  package='TeamsonUK.Usability.Data.Item.Stock',
  syntax='proto3',
  serialized_options=b'\n\'uk.co.teamson.usability.data.item.stockP\001\312\002#TeamsonUK\\Usability\\Data\\Item\\Stock',
  serialized_pb=b'\n*uk/data/item/stock/StockDeliveryInfo.proto\x12#TeamsonUK.Usability.Data.Item.Stock\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x01\n\x11StockDeliveryInfo\x12\x31\n\rdocument_date\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rdelivery_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0cposting_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x11\n\twarehouse\x18\x05 \x01(\tBQ\n\'uk.co.teamson.usability.data.item.stockP\x01\xca\x02#TeamsonUK\\Usability\\Data\\Item\\Stockb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_STOCKDELIVERYINFO = _descriptor.Descriptor(
  name='StockDeliveryInfo',
  full_name='TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='document_date', full_name='TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfo.document_date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivery_date', full_name='TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfo.delivery_date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='posting_date', full_name='TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfo.posting_date', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfo.quantity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse', full_name='TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfo.warehouse', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=325,
)

_STOCKDELIVERYINFO.fields_by_name['document_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STOCKDELIVERYINFO.fields_by_name['delivery_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STOCKDELIVERYINFO.fields_by_name['posting_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['StockDeliveryInfo'] = _STOCKDELIVERYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockDeliveryInfo = _reflection.GeneratedProtocolMessageType('StockDeliveryInfo', (_message.Message,), {
  'DESCRIPTOR' : _STOCKDELIVERYINFO,
  '__module__' : 'uk.data.item.stock.StockDeliveryInfo_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Data.Item.Stock.StockDeliveryInfo)
  })
_sym_db.RegisterMessage(StockDeliveryInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
