# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/data/item/stock/WarehouseStock.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/data/item/stock/WarehouseStock.proto',
  package='TeamsonUK.Usability.Data.Item.Stock',
  syntax='proto3',
  serialized_options=b'\n\'uk.co.teamson.usability.data.item.stockP\001\312\002#TeamsonUK\\Usability\\Data\\Item\\Stock',
  serialized_pb=b'\n\'uk/data/item/stock/WarehouseStock.proto\x12#TeamsonUK.Usability.Data.Item.Stock\"Y\n\x0eWarehouseStock\x12\x0f\n\x07on_hand\x18\x01 \x01(\x05\x12\x10\n\x08\x63ommited\x18\x02 \x01(\x05\x12\x11\n\tavailable\x18\x03 \x01(\x05\x12\x11\n\twarehouse\x18\x04 \x01(\tBQ\n\'uk.co.teamson.usability.data.item.stockP\x01\xca\x02#TeamsonUK\\Usability\\Data\\Item\\Stockb\x06proto3'
)




_WAREHOUSESTOCK = _descriptor.Descriptor(
  name='WarehouseStock',
  full_name='TeamsonUK.Usability.Data.Item.Stock.WarehouseStock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='on_hand', full_name='TeamsonUK.Usability.Data.Item.Stock.WarehouseStock.on_hand', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commited', full_name='TeamsonUK.Usability.Data.Item.Stock.WarehouseStock.commited', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='available', full_name='TeamsonUK.Usability.Data.Item.Stock.WarehouseStock.available', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse', full_name='TeamsonUK.Usability.Data.Item.Stock.WarehouseStock.warehouse', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['WarehouseStock'] = _WAREHOUSESTOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WarehouseStock = _reflection.GeneratedProtocolMessageType('WarehouseStock', (_message.Message,), {
  'DESCRIPTOR' : _WAREHOUSESTOCK,
  '__module__' : 'uk.data.item.stock.WarehouseStock_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Data.Item.Stock.WarehouseStock)
  })
_sym_db.RegisterMessage(WarehouseStock)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
