# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from uk.networking.requests.ar.sales_order import GetSalesOrderStatusRequest_pb2 as uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2
from uk.networking.responses.ar.sales_order import GetSalesOrderStatusResponse_pb2 as uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2


class GetBasicSalesOrderInfoServiceStub(object):
    """
    	Service for getting basic order information
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSalesOrderStatusByOrderNumber = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/GetSalesOrderStatusByOrderNumber',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.GetSalesOrderStatusByOrderNumberRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.GetSalesOrderStatusResponse.FromString,
                )
        self.GetSalesOrderStatusByDocumentEntry = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/GetSalesOrderStatusByDocumentEntry',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.GetSalesOrderStatusByDocumentEntryRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.GetSalesOrderStatusResponse.FromString,
                )
        self.GetSalesOrderStatusByCustomerInfo = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/GetSalesOrderStatusByCustomerInfo',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.GetSalesOrderStatusByCustomerInfoRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.GetSalesOrderStatusResponse.FromString,
                )
        self.BulkGetSalesOrderStatusByOrderNumber = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/BulkGetSalesOrderStatusByOrderNumber',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.BulkGetSalesOrderStatusByOrderNumberRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.BulkGetSalesOrderStatusByOrderNumberResponse.FromString,
                )
        self.BulkGetSalesOrderStatusByDocumentEntry = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/BulkGetSalesOrderStatusByDocumentEntry',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.BulkGetSalesOrderStatusByDocumentEntryRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.BulkGetSalesOrderStatusByDocumentEntryResponse.FromString,
                )
        self.BulkGetSalesOrderStatusByCustomerInfo = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/BulkGetSalesOrderStatusByCustomerInfo',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.BulkGetSalesOrderStatusByCustomerInfoRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.BulkGetSalesOrderStatusByCustomerInfoResponse.FromString,
                )


class GetBasicSalesOrderInfoServiceServicer(object):
    """
    	Service for getting basic order information
    """

    def GetSalesOrderStatusByOrderNumber(self, request, context):
        """RPC for getting order status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesOrderStatusByDocumentEntry(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesOrderStatusByCustomerInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkGetSalesOrderStatusByOrderNumber(self, request, context):
        """RPC for getting order statuses in bulk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkGetSalesOrderStatusByDocumentEntry(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkGetSalesOrderStatusByCustomerInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetBasicSalesOrderInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSalesOrderStatusByOrderNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesOrderStatusByOrderNumber,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.GetSalesOrderStatusByOrderNumberRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.GetSalesOrderStatusResponse.SerializeToString,
            ),
            'GetSalesOrderStatusByDocumentEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesOrderStatusByDocumentEntry,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.GetSalesOrderStatusByDocumentEntryRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.GetSalesOrderStatusResponse.SerializeToString,
            ),
            'GetSalesOrderStatusByCustomerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesOrderStatusByCustomerInfo,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.GetSalesOrderStatusByCustomerInfoRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.GetSalesOrderStatusResponse.SerializeToString,
            ),
            'BulkGetSalesOrderStatusByOrderNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkGetSalesOrderStatusByOrderNumber,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.BulkGetSalesOrderStatusByOrderNumberRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.BulkGetSalesOrderStatusByOrderNumberResponse.SerializeToString,
            ),
            'BulkGetSalesOrderStatusByDocumentEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkGetSalesOrderStatusByDocumentEntry,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.BulkGetSalesOrderStatusByDocumentEntryRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.BulkGetSalesOrderStatusByDocumentEntryResponse.SerializeToString,
            ),
            'BulkGetSalesOrderStatusByCustomerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkGetSalesOrderStatusByCustomerInfo,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.BulkGetSalesOrderStatusByCustomerInfoRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.BulkGetSalesOrderStatusByCustomerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetBasicSalesOrderInfoService(object):
    """
    	Service for getting basic order information
    """

    @staticmethod
    def GetSalesOrderStatusByOrderNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/GetSalesOrderStatusByOrderNumber',
            uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.GetSalesOrderStatusByOrderNumberRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.GetSalesOrderStatusResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSalesOrderStatusByDocumentEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/GetSalesOrderStatusByDocumentEntry',
            uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.GetSalesOrderStatusByDocumentEntryRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.GetSalesOrderStatusResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSalesOrderStatusByCustomerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/GetSalesOrderStatusByCustomerInfo',
            uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.GetSalesOrderStatusByCustomerInfoRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.GetSalesOrderStatusResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkGetSalesOrderStatusByOrderNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/BulkGetSalesOrderStatusByOrderNumber',
            uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.BulkGetSalesOrderStatusByOrderNumberRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.BulkGetSalesOrderStatusByOrderNumberResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkGetSalesOrderStatusByDocumentEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/BulkGetSalesOrderStatusByDocumentEntry',
            uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.BulkGetSalesOrderStatusByDocumentEntryRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.BulkGetSalesOrderStatusByDocumentEntryResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkGetSalesOrderStatusByCustomerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.GetBasicSalesOrderInfoService/BulkGetSalesOrderStatusByCustomerInfo',
            uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_GetSalesOrderStatusRequest__pb2.BulkGetSalesOrderStatusByCustomerInfoRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_GetSalesOrderStatusResponse__pb2.BulkGetSalesOrderStatusByCustomerInfoResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
