# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from uk.networking.requests.ar.sales_order import InsertBasicSalesOrderRequest_pb2 as uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_InsertBasicSalesOrderRequest__pb2
from uk.networking.responses.ar.sales_order import InsertBasicSalesOrderResponse_pb2 as uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_InsertBasicSalesOrderResponse__pb2


class InsertBasicSalesOrderServiceStub(object):
    """
    	Service for inserting orders
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertBasicSalesOrder = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.InsertBasicSalesOrderService/InsertBasicSalesOrder',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_InsertBasicSalesOrderRequest__pb2.InsertBasicSalesOrderRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_InsertBasicSalesOrderResponse__pb2.InsertBasicSalesOrderResponse.FromString,
                )


class InsertBasicSalesOrderServiceServicer(object):
    """
    	Service for inserting orders
    """

    def InsertBasicSalesOrder(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InsertBasicSalesOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertBasicSalesOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertBasicSalesOrder,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_InsertBasicSalesOrderRequest__pb2.InsertBasicSalesOrderRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_InsertBasicSalesOrderResponse__pb2.InsertBasicSalesOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TeamsonUK.Usability.Networking.Services.AR.SalesOrder.InsertBasicSalesOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InsertBasicSalesOrderService(object):
    """
    	Service for inserting orders
    """

    @staticmethod
    def InsertBasicSalesOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.SalesOrder.InsertBasicSalesOrderService/InsertBasicSalesOrder',
            uk_dot_networking_dot_requests_dot_ar_dot_sales__order_dot_InsertBasicSalesOrderRequest__pb2.InsertBasicSalesOrderRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_sales__order_dot_InsertBasicSalesOrderResponse__pb2.InsertBasicSalesOrderResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
