# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/networking/services/ar/delivery_order/AddDeliveryTrackingService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from uk.networking.requests.ar.delivery_order import AddDeliveryTrackingRequest_pb2 as uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2
from uk.networking.responses.ar.delivery_order import AddDeliveryTrackingResponse_pb2 as uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/networking/services/ar/delivery_order/AddDeliveryTrackingService.proto',
  package='TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder',
  syntax='proto3',
  serialized_options=b'\n<uk.co.teamson.usability.networking.services.ar.deliveryorderP\001\312\0028TeamsonUK\\Usability\\Networking\\Services\\AR\\DeliveryOrder',
  serialized_pb=b'\nIuk/networking/services/ar/delivery_order/AddDeliveryTrackingService.proto\x12\x38TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder\x1aIuk/networking/requests/ar/delivery_order/AddDeliveryTrackingRequest.proto\x1aKuk/networking/responses/ar/delivery_order/AddDeliveryTrackingResponse.proto2\xc8\x05\n\x1a\x41\x64\x64\x44\x65liveryTrackingService\x12\xdf\x01\n AddDeliveryTrackingByOrderNumber\x12\x61.TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByOrderNumberRequest\x1aV.TeamsonUK.Usability.Networking.Responses.AR.DeliveryOrder.AddDeliveryTrackingResponse\"\x00\x12\xe3\x01\n\"AddDeliveryTrackingByDocumentEntry\x12\x63.TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByDocumentEntryRequest\x1aV.TeamsonUK.Usability.Networking.Responses.AR.DeliveryOrder.AddDeliveryTrackingResponse\"\x00\x12\xe1\x01\n!AddDeliveryTrackingByCustomerInfo\x12\x62.TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByCustomerInfoRequest\x1aV.TeamsonUK.Usability.Networking.Responses.AR.DeliveryOrder.AddDeliveryTrackingResponse\"\x00\x42{\n<uk.co.teamson.usability.networking.services.ar.deliveryorderP\x01\xca\x02\x38TeamsonUK\\Usability\\Networking\\Services\\AR\\DeliveryOrderb\x06proto3'
  ,
  dependencies=[uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2.DESCRIPTOR,uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ADDDELIVERYTRACKINGSERVICE = _descriptor.ServiceDescriptor(
  name='AddDeliveryTrackingService',
  full_name='TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=288,
  serialized_end=1000,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddDeliveryTrackingByOrderNumber',
    full_name='TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService.AddDeliveryTrackingByOrderNumber',
    index=0,
    containing_service=None,
    input_type=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2._ADDDELIVERYTRACKINGBYORDERNUMBERREQUEST,
    output_type=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2._ADDDELIVERYTRACKINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddDeliveryTrackingByDocumentEntry',
    full_name='TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService.AddDeliveryTrackingByDocumentEntry',
    index=1,
    containing_service=None,
    input_type=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2._ADDDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST,
    output_type=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2._ADDDELIVERYTRACKINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddDeliveryTrackingByCustomerInfo',
    full_name='TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService.AddDeliveryTrackingByCustomerInfo',
    index=2,
    containing_service=None,
    input_type=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2._ADDDELIVERYTRACKINGBYCUSTOMERINFOREQUEST,
    output_type=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2._ADDDELIVERYTRACKINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDDELIVERYTRACKINGSERVICE)

DESCRIPTOR.services_by_name['AddDeliveryTrackingService'] = _ADDDELIVERYTRACKINGSERVICE

# @@protoc_insertion_point(module_scope)
