# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from uk.networking.requests.ar.delivery_order import AddDeliveryTrackingRequest_pb2 as uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2
from uk.networking.responses.ar.delivery_order import AddDeliveryTrackingResponse_pb2 as uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2


class AddDeliveryTrackingServiceStub(object):
    """
    	Service for adding tracking to delivery orders
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDeliveryTrackingByOrderNumber = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService/AddDeliveryTrackingByOrderNumber',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2.AddDeliveryTrackingByOrderNumberRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2.AddDeliveryTrackingResponse.FromString,
                )
        self.AddDeliveryTrackingByDocumentEntry = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService/AddDeliveryTrackingByDocumentEntry',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2.AddDeliveryTrackingByDocumentEntryRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2.AddDeliveryTrackingResponse.FromString,
                )
        self.AddDeliveryTrackingByCustomerInfo = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService/AddDeliveryTrackingByCustomerInfo',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2.AddDeliveryTrackingByCustomerInfoRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2.AddDeliveryTrackingResponse.FromString,
                )


class AddDeliveryTrackingServiceServicer(object):
    """
    	Service for adding tracking to delivery orders
    """

    def AddDeliveryTrackingByOrderNumber(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDeliveryTrackingByDocumentEntry(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDeliveryTrackingByCustomerInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddDeliveryTrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDeliveryTrackingByOrderNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDeliveryTrackingByOrderNumber,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2.AddDeliveryTrackingByOrderNumberRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2.AddDeliveryTrackingResponse.SerializeToString,
            ),
            'AddDeliveryTrackingByDocumentEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDeliveryTrackingByDocumentEntry,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2.AddDeliveryTrackingByDocumentEntryRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2.AddDeliveryTrackingResponse.SerializeToString,
            ),
            'AddDeliveryTrackingByCustomerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDeliveryTrackingByCustomerInfo,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2.AddDeliveryTrackingByCustomerInfoRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2.AddDeliveryTrackingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AddDeliveryTrackingService(object):
    """
    	Service for adding tracking to delivery orders
    """

    @staticmethod
    def AddDeliveryTrackingByOrderNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService/AddDeliveryTrackingByOrderNumber',
            uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2.AddDeliveryTrackingByOrderNumberRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2.AddDeliveryTrackingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddDeliveryTrackingByDocumentEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService/AddDeliveryTrackingByDocumentEntry',
            uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2.AddDeliveryTrackingByDocumentEntryRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2.AddDeliveryTrackingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddDeliveryTrackingByCustomerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.AddDeliveryTrackingService/AddDeliveryTrackingByCustomerInfo',
            uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingRequest__pb2.AddDeliveryTrackingByCustomerInfoRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_AddDeliveryTrackingResponse__pb2.AddDeliveryTrackingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
