# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from uk.networking.requests.ar.delivery_order import GetDeliveryTrackingRequest_pb2 as uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2
from uk.networking.responses.ar.delivery_order import GetDeliveryTrackingResponse_pb2 as uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2


class GetDeliveryTrackingServiceStub(object):
    """
    	Service for adding tracking to delivery orders
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeliveryTrackingByOrderNumber = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/GetDeliveryTrackingByOrderNumber',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.GetDeliveryTrackingByOrderNumberRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.GetDeliveryTrackingResponse.FromString,
                )
        self.GetDeliveryTrackingByDocumentEntry = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/GetDeliveryTrackingByDocumentEntry',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.GetDeliveryTrackingByDocumentEntryRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.GetDeliveryTrackingResponse.FromString,
                )
        self.GetDeliveryTrackingByCustomerInfo = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/GetDeliveryTrackingByCustomerInfo',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.GetDeliveryTrackingByCustomerInfoRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.GetDeliveryTrackingResponse.FromString,
                )
        self.BulkGetDeliveryTrackingByOrderNumber = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/BulkGetDeliveryTrackingByOrderNumber',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.BulkGetDeliveryTrackingByOrderNumberRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.BulkGetDeliveryTrackingByOrderNumberResponse.FromString,
                )
        self.BulkGetDeliveryTrackingByDocumentEntry = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/BulkGetDeliveryTrackingByDocumentEntry',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.BulkGetDeliveryTrackingByDocumentEntryRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.BulkGetDeliveryTrackingByDocumentEntryResponse.FromString,
                )
        self.BulkGetDeliveryTrackingByCustomerInfo = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/BulkGetDeliveryTrackingByCustomerInfo',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.BulkGetDeliveryTrackingByCustomerInfoRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.BulkGetDeliveryTrackingByCustomerInfoResponse.FromString,
                )


class GetDeliveryTrackingServiceServicer(object):
    """
    	Service for adding tracking to delivery orders
    """

    def GetDeliveryTrackingByOrderNumber(self, request, context):
        """Single operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeliveryTrackingByDocumentEntry(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeliveryTrackingByCustomerInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkGetDeliveryTrackingByOrderNumber(self, request, context):
        """Bulk operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkGetDeliveryTrackingByDocumentEntry(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkGetDeliveryTrackingByCustomerInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetDeliveryTrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeliveryTrackingByOrderNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeliveryTrackingByOrderNumber,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.GetDeliveryTrackingByOrderNumberRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.GetDeliveryTrackingResponse.SerializeToString,
            ),
            'GetDeliveryTrackingByDocumentEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeliveryTrackingByDocumentEntry,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.GetDeliveryTrackingByDocumentEntryRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.GetDeliveryTrackingResponse.SerializeToString,
            ),
            'GetDeliveryTrackingByCustomerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeliveryTrackingByCustomerInfo,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.GetDeliveryTrackingByCustomerInfoRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.GetDeliveryTrackingResponse.SerializeToString,
            ),
            'BulkGetDeliveryTrackingByOrderNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkGetDeliveryTrackingByOrderNumber,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.BulkGetDeliveryTrackingByOrderNumberRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.BulkGetDeliveryTrackingByOrderNumberResponse.SerializeToString,
            ),
            'BulkGetDeliveryTrackingByDocumentEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkGetDeliveryTrackingByDocumentEntry,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.BulkGetDeliveryTrackingByDocumentEntryRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.BulkGetDeliveryTrackingByDocumentEntryResponse.SerializeToString,
            ),
            'BulkGetDeliveryTrackingByCustomerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkGetDeliveryTrackingByCustomerInfo,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.BulkGetDeliveryTrackingByCustomerInfoRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.BulkGetDeliveryTrackingByCustomerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetDeliveryTrackingService(object):
    """
    	Service for adding tracking to delivery orders
    """

    @staticmethod
    def GetDeliveryTrackingByOrderNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/GetDeliveryTrackingByOrderNumber',
            uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.GetDeliveryTrackingByOrderNumberRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.GetDeliveryTrackingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeliveryTrackingByDocumentEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/GetDeliveryTrackingByDocumentEntry',
            uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.GetDeliveryTrackingByDocumentEntryRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.GetDeliveryTrackingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeliveryTrackingByCustomerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/GetDeliveryTrackingByCustomerInfo',
            uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.GetDeliveryTrackingByCustomerInfoRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.GetDeliveryTrackingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkGetDeliveryTrackingByOrderNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/BulkGetDeliveryTrackingByOrderNumber',
            uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.BulkGetDeliveryTrackingByOrderNumberRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.BulkGetDeliveryTrackingByOrderNumberResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkGetDeliveryTrackingByDocumentEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/BulkGetDeliveryTrackingByDocumentEntry',
            uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.BulkGetDeliveryTrackingByDocumentEntryRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.BulkGetDeliveryTrackingByDocumentEntryResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkGetDeliveryTrackingByCustomerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.GetDeliveryTrackingService/BulkGetDeliveryTrackingByCustomerInfo',
            uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingRequest__pb2.BulkGetDeliveryTrackingByCustomerInfoRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_GetDeliveryTrackingResponse__pb2.BulkGetDeliveryTrackingByCustomerInfoResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
