# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from uk.networking.requests.ar.delivery_order import InsertDeliveryLineUploadLogRequest_pb2 as uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_InsertDeliveryLineUploadLogRequest__pb2
from uk.networking.responses.ar.delivery_order import InsertDeliveryLineUploadLogResponse_pb2 as uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_InsertDeliveryLineUploadLogResponse__pb2


class InsertDeliveryLineUploadLogServiceStub(object):
    """
    	Service inserting log information for delivery lines being uploaded
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertDeliveryLineUploadLog = channel.unary_unary(
                '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.InsertDeliveryLineUploadLogService/InsertDeliveryLineUploadLog',
                request_serializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_InsertDeliveryLineUploadLogRequest__pb2.InsertDeliveryLineUploadLogRequest.SerializeToString,
                response_deserializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_InsertDeliveryLineUploadLogResponse__pb2.InsertDeliveryLineUploadLogResponse.FromString,
                )


class InsertDeliveryLineUploadLogServiceServicer(object):
    """
    	Service inserting log information for delivery lines being uploaded
    """

    def InsertDeliveryLineUploadLog(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InsertDeliveryLineUploadLogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertDeliveryLineUploadLog': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertDeliveryLineUploadLog,
                    request_deserializer=uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_InsertDeliveryLineUploadLogRequest__pb2.InsertDeliveryLineUploadLogRequest.FromString,
                    response_serializer=uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_InsertDeliveryLineUploadLogResponse__pb2.InsertDeliveryLineUploadLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.InsertDeliveryLineUploadLogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InsertDeliveryLineUploadLogService(object):
    """
    	Service inserting log information for delivery lines being uploaded
    """

    @staticmethod
    def InsertDeliveryLineUploadLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamsonUK.Usability.Networking.Services.AR.DeliveryOrder.InsertDeliveryLineUploadLogService/InsertDeliveryLineUploadLog',
            uk_dot_networking_dot_requests_dot_ar_dot_delivery__order_dot_InsertDeliveryLineUploadLogRequest__pb2.InsertDeliveryLineUploadLogRequest.SerializeToString,
            uk_dot_networking_dot_responses_dot_ar_dot_delivery__order_dot_InsertDeliveryLineUploadLogResponse__pb2.InsertDeliveryLineUploadLogResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
