# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/networking/responses/ar/delivery_order/AddDeliveryTrackingResponse.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/networking/responses/ar/delivery_order/AddDeliveryTrackingResponse.proto',
  package='TeamsonUK.Usability.Networking.Responses.AR.DeliveryOrder',
  syntax='proto3',
  serialized_options=b'\n=uk.co.teamson.usability.networking.responses.ar.deliveryorderP\001\312\0029TeamsonUK\\Usability\\Networking\\Responses\\AR\\DeliveryOrder',
  serialized_pb=b'\nKuk/networking/responses/ar/delivery_order/AddDeliveryTrackingResponse.proto\x12\x39TeamsonUK.Usability.Networking.Responses.AR.DeliveryOrder\"\x1d\n\x1b\x41\x64\x64\x44\x65liveryTrackingResponseB}\n=uk.co.teamson.usability.networking.responses.ar.deliveryorderP\x01\xca\x02\x39TeamsonUK\\Usability\\Networking\\Responses\\AR\\DeliveryOrderb\x06proto3'
)




_ADDDELIVERYTRACKINGRESPONSE = _descriptor.Descriptor(
  name='AddDeliveryTrackingResponse',
  full_name='TeamsonUK.Usability.Networking.Responses.AR.DeliveryOrder.AddDeliveryTrackingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['AddDeliveryTrackingResponse'] = _ADDDELIVERYTRACKINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddDeliveryTrackingResponse = _reflection.GeneratedProtocolMessageType('AddDeliveryTrackingResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDDELIVERYTRACKINGRESPONSE,
  '__module__' : 'uk.networking.responses.ar.delivery_order.AddDeliveryTrackingResponse_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Responses.AR.DeliveryOrder.AddDeliveryTrackingResponse)
  })
_sym_db.RegisterMessage(AddDeliveryTrackingResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
