# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/networking/requests/ar/delivery_order/AddDeliveryTrackingRequest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/networking/requests/ar/delivery_order/AddDeliveryTrackingRequest.proto',
  package='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder',
  syntax='proto3',
  serialized_options=b'\n<uk.co.teamson.usability.networking.requests.ar.deliveryorderP\001\312\0028TeamsonUK\\Usability\\Networking\\Requests\\AR\\DeliveryOrder',
  serialized_pb=b'\nIuk/networking/requests/ar/delivery_order/AddDeliveryTrackingRequest.proto\x12\x38TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x01\n)AddDeliveryTrackingByDocumentEntryRequest\x12\x16\n\x0e\x64ocument_entry\x18\x01 \x01(\t\x12\x17\n\x0ftracking_number\x18\x02 \x01(\t\x12\x36\n\x12tracking_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x90\x01\n\'AddDeliveryTrackingByOrderNumberRequest\x12\x14\n\x0corder_number\x18\x01 \x01(\t\x12\x17\n\x0ftracking_number\x18\x02 \x01(\t\x12\x36\n\x12tracking_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xb4\x01\n(AddDeliveryTrackingByCustomerInfoRequest\x12\x18\n\x10\x62usiness_partner\x18\x01 \x01(\t\x12\x1d\n\x15\x63ustomer_order_number\x18\x02 \x01(\t\x12\x17\n\x0ftracking_number\x18\x03 \x01(\t\x12\x36\n\x12tracking_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB{\n<uk.co.teamson.usability.networking.requests.ar.deliveryorderP\x01\xca\x02\x38TeamsonUK\\Usability\\Networking\\Requests\\AR\\DeliveryOrderb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ADDDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST = _descriptor.Descriptor(
  name='AddDeliveryTrackingByDocumentEntryRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByDocumentEntryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='document_entry', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByDocumentEntryRequest.document_entry', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_number', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByDocumentEntryRequest.tracking_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_timestamp', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByDocumentEntryRequest.tracking_timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=317,
)


_ADDDELIVERYTRACKINGBYORDERNUMBERREQUEST = _descriptor.Descriptor(
  name='AddDeliveryTrackingByOrderNumberRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByOrderNumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_number', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByOrderNumberRequest.order_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_number', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByOrderNumberRequest.tracking_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_timestamp', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByOrderNumberRequest.tracking_timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=464,
)


_ADDDELIVERYTRACKINGBYCUSTOMERINFOREQUEST = _descriptor.Descriptor(
  name='AddDeliveryTrackingByCustomerInfoRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByCustomerInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='business_partner', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByCustomerInfoRequest.business_partner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customer_order_number', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByCustomerInfoRequest.customer_order_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_number', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByCustomerInfoRequest.tracking_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_timestamp', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByCustomerInfoRequest.tracking_timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=647,
)

_ADDDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST.fields_by_name['tracking_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ADDDELIVERYTRACKINGBYORDERNUMBERREQUEST.fields_by_name['tracking_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ADDDELIVERYTRACKINGBYCUSTOMERINFOREQUEST.fields_by_name['tracking_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['AddDeliveryTrackingByDocumentEntryRequest'] = _ADDDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST
DESCRIPTOR.message_types_by_name['AddDeliveryTrackingByOrderNumberRequest'] = _ADDDELIVERYTRACKINGBYORDERNUMBERREQUEST
DESCRIPTOR.message_types_by_name['AddDeliveryTrackingByCustomerInfoRequest'] = _ADDDELIVERYTRACKINGBYCUSTOMERINFOREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddDeliveryTrackingByDocumentEntryRequest = _reflection.GeneratedProtocolMessageType('AddDeliveryTrackingByDocumentEntryRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.AddDeliveryTrackingRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByDocumentEntryRequest)
  })
_sym_db.RegisterMessage(AddDeliveryTrackingByDocumentEntryRequest)

AddDeliveryTrackingByOrderNumberRequest = _reflection.GeneratedProtocolMessageType('AddDeliveryTrackingByOrderNumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDDELIVERYTRACKINGBYORDERNUMBERREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.AddDeliveryTrackingRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByOrderNumberRequest)
  })
_sym_db.RegisterMessage(AddDeliveryTrackingByOrderNumberRequest)

AddDeliveryTrackingByCustomerInfoRequest = _reflection.GeneratedProtocolMessageType('AddDeliveryTrackingByCustomerInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDDELIVERYTRACKINGBYCUSTOMERINFOREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.AddDeliveryTrackingRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.AddDeliveryTrackingByCustomerInfoRequest)
  })
_sym_db.RegisterMessage(AddDeliveryTrackingByCustomerInfoRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
