# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/networking/requests/ar/delivery_order/GetBasicDeliveryOrdersRequest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from uk.data.ar.delivery_order import BasicDeliveryOrder_pb2 as uk_dot_data_dot_ar_dot_delivery__order_dot_BasicDeliveryOrder__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/networking/requests/ar/delivery_order/GetBasicDeliveryOrdersRequest.proto',
  package='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder',
  syntax='proto3',
  serialized_options=b'\n<uk.co.teamson.usability.networking.requests.ar.deliveryorderP\001\312\0028TeamsonUK\\Usability\\Networking\\Requests\\AR\\DeliveryOrder',
  serialized_pb=b'\nLuk/networking/requests/ar/delivery_order/GetBasicDeliveryOrdersRequest.proto\x12\x38TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder\x1a\x32uk/data/ar/delivery_order/BasicDeliveryOrder.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x08\n\x1dGetBasicDeliveryOrdersRequest\x12\x34\n\x10\x63reate_date_from\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0e\x63reate_date_to\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x36\n\x12\x64ocument_date_from\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10\x64ocument_date_to\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x36\n\x12\x64\x65livery_date_from\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10\x64\x65livery_date_to\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x11posting_date_from\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0fposting_date_to\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10specified_orders\x18\t \x03(\t\x12\x97\x01\n\x19specified_customer_orders\x18\n \x03(\x0b\x32t.TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.SpecifiedCustomerOrdersEntry\x12\x1c\n\x14specified_warehouses\x18\x0b \x03(\t\x12\x1b\n\x13specified_customers\x18\x0c \x03(\t\x12\x1e\n\x16specified_ship_methods\x18\r \x03(\t\x12\x17\n\x0fspecified_items\x18\x0e \x03(\t\x12\x65\n\x12specified_statuses\x18\x0f \x03(\x0e\x32I.TeamsonUK.Usability.Data.AR.DeliveryOrder.BasicDeliveryOrder.OrderStatus\x12\x66\n\x15specified_order_types\x18\x10 \x03(\x0e\x32G.TeamsonUK.Usability.Data.AR.DeliveryOrder.BasicDeliveryOrder.OrderType\x12\x1d\n\x15\x66ilter_uploaded_lines\x18\x11 \x01(\x08\x1a>\n\x1cSpecifiedCustomerOrdersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42{\n<uk.co.teamson.usability.networking.requests.ar.deliveryorderP\x01\xca\x02\x38TeamsonUK\\Usability\\Networking\\Requests\\AR\\DeliveryOrderb\x06proto3'
  ,
  dependencies=[uk_dot_data_dot_ar_dot_delivery__order_dot_BasicDeliveryOrder__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_GETBASICDELIVERYORDERSREQUEST_SPECIFIEDCUSTOMERORDERSENTRY = _descriptor.Descriptor(
  name='SpecifiedCustomerOrdersEntry',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.SpecifiedCustomerOrdersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.SpecifiedCustomerOrdersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.SpecifiedCustomerOrdersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1225,
  serialized_end=1287,
)

_GETBASICDELIVERYORDERSREQUEST = _descriptor.Descriptor(
  name='GetBasicDeliveryOrdersRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='create_date_from', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.create_date_from', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_date_to', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.create_date_to', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='document_date_from', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.document_date_from', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='document_date_to', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.document_date_to', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivery_date_from', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.delivery_date_from', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivery_date_to', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.delivery_date_to', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='posting_date_from', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.posting_date_from', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='posting_date_to', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.posting_date_to', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_orders', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.specified_orders', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_customer_orders', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.specified_customer_orders', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_warehouses', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.specified_warehouses', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_customers', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.specified_customers', index=11,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_ship_methods', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.specified_ship_methods', index=12,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_items', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.specified_items', index=13,
      number=14, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_statuses', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.specified_statuses', index=14,
      number=15, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specified_order_types', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.specified_order_types', index=15,
      number=16, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter_uploaded_lines', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.filter_uploaded_lines', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETBASICDELIVERYORDERSREQUEST_SPECIFIEDCUSTOMERORDERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=1287,
)

_GETBASICDELIVERYORDERSREQUEST_SPECIFIEDCUSTOMERORDERSENTRY.containing_type = _GETBASICDELIVERYORDERSREQUEST
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['create_date_from'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['create_date_to'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['document_date_from'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['document_date_to'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['delivery_date_from'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['delivery_date_to'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['posting_date_from'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['posting_date_to'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['specified_customer_orders'].message_type = _GETBASICDELIVERYORDERSREQUEST_SPECIFIEDCUSTOMERORDERSENTRY
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['specified_statuses'].enum_type = uk_dot_data_dot_ar_dot_delivery__order_dot_BasicDeliveryOrder__pb2._BASICDELIVERYORDER_ORDERSTATUS
_GETBASICDELIVERYORDERSREQUEST.fields_by_name['specified_order_types'].enum_type = uk_dot_data_dot_ar_dot_delivery__order_dot_BasicDeliveryOrder__pb2._BASICDELIVERYORDER_ORDERTYPE
DESCRIPTOR.message_types_by_name['GetBasicDeliveryOrdersRequest'] = _GETBASICDELIVERYORDERSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetBasicDeliveryOrdersRequest = _reflection.GeneratedProtocolMessageType('GetBasicDeliveryOrdersRequest', (_message.Message,), {

  'SpecifiedCustomerOrdersEntry' : _reflection.GeneratedProtocolMessageType('SpecifiedCustomerOrdersEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETBASICDELIVERYORDERSREQUEST_SPECIFIEDCUSTOMERORDERSENTRY,
    '__module__' : 'uk.networking.requests.ar.delivery_order.GetBasicDeliveryOrdersRequest_pb2'
    # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest.SpecifiedCustomerOrdersEntry)
    })
  ,
  'DESCRIPTOR' : _GETBASICDELIVERYORDERSREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.GetBasicDeliveryOrdersRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetBasicDeliveryOrdersRequest)
  })
_sym_db.RegisterMessage(GetBasicDeliveryOrdersRequest)
_sym_db.RegisterMessage(GetBasicDeliveryOrdersRequest.SpecifiedCustomerOrdersEntry)


DESCRIPTOR._options = None
_GETBASICDELIVERYORDERSREQUEST_SPECIFIEDCUSTOMERORDERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
