# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/networking/requests/ar/delivery_order/GetDeliveryTrackingRequest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/networking/requests/ar/delivery_order/GetDeliveryTrackingRequest.proto',
  package='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder',
  syntax='proto3',
  serialized_options=b'\n<uk.co.teamson.usability.networking.requests.ar.deliveryorderP\001\312\0028TeamsonUK\\Usability\\Networking\\Requests\\AR\\DeliveryOrder',
  serialized_pb=b'\nIuk/networking/requests/ar/delivery_order/GetDeliveryTrackingRequest.proto\x12\x38TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder\"?\n\'GetDeliveryTrackingByOrderNumberRequest\x12\x14\n\x0corder_number\x18\x01 \x01(\t\"C\n)GetDeliveryTrackingByDocumentEntryRequest\x12\x16\n\x0e\x64ocument_entry\x18\x01 \x01(\t\"c\n(GetDeliveryTrackingByCustomerInfoRequest\x12\x1d\n\x15\x63ustomer_order_number\x18\x01 \x01(\t\x12\x18\n\x10\x62usiness_partner\x18\x02 \x01(\t\"D\n+BulkGetDeliveryTrackingByOrderNumberRequest\x12\x15\n\rorder_numbers\x18\x01 \x03(\t\"I\n-BulkGetDeliveryTrackingByDocumentEntryRequest\x12\x18\n\x10\x64ocument_entries\x18\x01 \x03(\t\"\x8a\x02\n,BulkGetDeliveryTrackingByCustomerInfoRequest\x12\x8d\x01\n\rcustomer_sets\x18\x01 \x03(\x0b\x32v.TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByCustomerInfoRequest.CustomerInfoSet\x1aJ\n\x0f\x43ustomerInfoSet\x12\x1d\n\x15\x63ustomer_order_number\x18\x01 \x01(\t\x12\x18\n\x10\x62usiness_partner\x18\x02 \x01(\tB{\n<uk.co.teamson.usability.networking.requests.ar.deliveryorderP\x01\xca\x02\x38TeamsonUK\\Usability\\Networking\\Requests\\AR\\DeliveryOrderb\x06proto3'
)




_GETDELIVERYTRACKINGBYORDERNUMBERREQUEST = _descriptor.Descriptor(
  name='GetDeliveryTrackingByOrderNumberRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetDeliveryTrackingByOrderNumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_number', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetDeliveryTrackingByOrderNumberRequest.order_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=198,
)


_GETDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST = _descriptor.Descriptor(
  name='GetDeliveryTrackingByDocumentEntryRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetDeliveryTrackingByDocumentEntryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='document_entry', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetDeliveryTrackingByDocumentEntryRequest.document_entry', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=267,
)


_GETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST = _descriptor.Descriptor(
  name='GetDeliveryTrackingByCustomerInfoRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetDeliveryTrackingByCustomerInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_order_number', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetDeliveryTrackingByCustomerInfoRequest.customer_order_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='business_partner', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetDeliveryTrackingByCustomerInfoRequest.business_partner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=368,
)


_BULKGETDELIVERYTRACKINGBYORDERNUMBERREQUEST = _descriptor.Descriptor(
  name='BulkGetDeliveryTrackingByOrderNumberRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByOrderNumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_numbers', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByOrderNumberRequest.order_numbers', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=438,
)


_BULKGETDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST = _descriptor.Descriptor(
  name='BulkGetDeliveryTrackingByDocumentEntryRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByDocumentEntryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='document_entries', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByDocumentEntryRequest.document_entries', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=513,
)


_BULKGETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST_CUSTOMERINFOSET = _descriptor.Descriptor(
  name='CustomerInfoSet',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByCustomerInfoRequest.CustomerInfoSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_order_number', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByCustomerInfoRequest.CustomerInfoSet.customer_order_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='business_partner', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByCustomerInfoRequest.CustomerInfoSet.business_partner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=782,
)

_BULKGETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST = _descriptor.Descriptor(
  name='BulkGetDeliveryTrackingByCustomerInfoRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByCustomerInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_sets', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByCustomerInfoRequest.customer_sets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BULKGETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST_CUSTOMERINFOSET, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=782,
)

_BULKGETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST_CUSTOMERINFOSET.containing_type = _BULKGETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST
_BULKGETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST.fields_by_name['customer_sets'].message_type = _BULKGETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST_CUSTOMERINFOSET
DESCRIPTOR.message_types_by_name['GetDeliveryTrackingByOrderNumberRequest'] = _GETDELIVERYTRACKINGBYORDERNUMBERREQUEST
DESCRIPTOR.message_types_by_name['GetDeliveryTrackingByDocumentEntryRequest'] = _GETDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST
DESCRIPTOR.message_types_by_name['GetDeliveryTrackingByCustomerInfoRequest'] = _GETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST
DESCRIPTOR.message_types_by_name['BulkGetDeliveryTrackingByOrderNumberRequest'] = _BULKGETDELIVERYTRACKINGBYORDERNUMBERREQUEST
DESCRIPTOR.message_types_by_name['BulkGetDeliveryTrackingByDocumentEntryRequest'] = _BULKGETDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST
DESCRIPTOR.message_types_by_name['BulkGetDeliveryTrackingByCustomerInfoRequest'] = _BULKGETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetDeliveryTrackingByOrderNumberRequest = _reflection.GeneratedProtocolMessageType('GetDeliveryTrackingByOrderNumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDELIVERYTRACKINGBYORDERNUMBERREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.GetDeliveryTrackingRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetDeliveryTrackingByOrderNumberRequest)
  })
_sym_db.RegisterMessage(GetDeliveryTrackingByOrderNumberRequest)

GetDeliveryTrackingByDocumentEntryRequest = _reflection.GeneratedProtocolMessageType('GetDeliveryTrackingByDocumentEntryRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.GetDeliveryTrackingRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetDeliveryTrackingByDocumentEntryRequest)
  })
_sym_db.RegisterMessage(GetDeliveryTrackingByDocumentEntryRequest)

GetDeliveryTrackingByCustomerInfoRequest = _reflection.GeneratedProtocolMessageType('GetDeliveryTrackingByCustomerInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.GetDeliveryTrackingRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.GetDeliveryTrackingByCustomerInfoRequest)
  })
_sym_db.RegisterMessage(GetDeliveryTrackingByCustomerInfoRequest)

BulkGetDeliveryTrackingByOrderNumberRequest = _reflection.GeneratedProtocolMessageType('BulkGetDeliveryTrackingByOrderNumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _BULKGETDELIVERYTRACKINGBYORDERNUMBERREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.GetDeliveryTrackingRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByOrderNumberRequest)
  })
_sym_db.RegisterMessage(BulkGetDeliveryTrackingByOrderNumberRequest)

BulkGetDeliveryTrackingByDocumentEntryRequest = _reflection.GeneratedProtocolMessageType('BulkGetDeliveryTrackingByDocumentEntryRequest', (_message.Message,), {
  'DESCRIPTOR' : _BULKGETDELIVERYTRACKINGBYDOCUMENTENTRYREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.GetDeliveryTrackingRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByDocumentEntryRequest)
  })
_sym_db.RegisterMessage(BulkGetDeliveryTrackingByDocumentEntryRequest)

BulkGetDeliveryTrackingByCustomerInfoRequest = _reflection.GeneratedProtocolMessageType('BulkGetDeliveryTrackingByCustomerInfoRequest', (_message.Message,), {

  'CustomerInfoSet' : _reflection.GeneratedProtocolMessageType('CustomerInfoSet', (_message.Message,), {
    'DESCRIPTOR' : _BULKGETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST_CUSTOMERINFOSET,
    '__module__' : 'uk.networking.requests.ar.delivery_order.GetDeliveryTrackingRequest_pb2'
    # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByCustomerInfoRequest.CustomerInfoSet)
    })
  ,
  'DESCRIPTOR' : _BULKGETDELIVERYTRACKINGBYCUSTOMERINFOREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.GetDeliveryTrackingRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.BulkGetDeliveryTrackingByCustomerInfoRequest)
  })
_sym_db.RegisterMessage(BulkGetDeliveryTrackingByCustomerInfoRequest)
_sym_db.RegisterMessage(BulkGetDeliveryTrackingByCustomerInfoRequest.CustomerInfoSet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
