# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uk/networking/requests/ar/delivery_order/InsertDeliveryLineUploadLogRequest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='uk/networking/requests/ar/delivery_order/InsertDeliveryLineUploadLogRequest.proto',
  package='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder',
  syntax='proto3',
  serialized_options=b'\n<uk.co.teamson.usability.networking.requests.ar.deliveryorderP\001\312\0028TeamsonUK\\Usability\\Networking\\Requests\\AR\\DeliveryOrder',
  serialized_pb=b'\nQuk/networking/requests/ar/delivery_order/InsertDeliveryLineUploadLogRequest.proto\x12\x38TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n\"InsertDeliveryLineUploadLogRequest\x12\x16\n\x0e\x64ocument_entry\x18\x01 \x01(\x03\x12\x17\n\x0f\x64ocument_number\x18\x02 \x01(\t\x12\x13\n\x0bline_number\x18\x03 \x01(\x05\x12\x34\n\x10upload_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10upload_warehouse\x18\x05 \x01(\tB{\n<uk.co.teamson.usability.networking.requests.ar.deliveryorderP\x01\xca\x02\x38TeamsonUK\\Usability\\Networking\\Requests\\AR\\DeliveryOrderb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_INSERTDELIVERYLINEUPLOADLOGREQUEST = _descriptor.Descriptor(
  name='InsertDeliveryLineUploadLogRequest',
  full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.InsertDeliveryLineUploadLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='document_entry', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.InsertDeliveryLineUploadLogRequest.document_entry', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='document_number', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.InsertDeliveryLineUploadLogRequest.document_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line_number', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.InsertDeliveryLineUploadLogRequest.line_number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upload_timestamp', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.InsertDeliveryLineUploadLogRequest.upload_timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upload_warehouse', full_name='TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.InsertDeliveryLineUploadLogRequest.upload_warehouse', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=363,
)

_INSERTDELIVERYLINEUPLOADLOGREQUEST.fields_by_name['upload_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['InsertDeliveryLineUploadLogRequest'] = _INSERTDELIVERYLINEUPLOADLOGREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InsertDeliveryLineUploadLogRequest = _reflection.GeneratedProtocolMessageType('InsertDeliveryLineUploadLogRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTDELIVERYLINEUPLOADLOGREQUEST,
  '__module__' : 'uk.networking.requests.ar.delivery_order.InsertDeliveryLineUploadLogRequest_pb2'
  # @@protoc_insertion_point(class_scope:TeamsonUK.Usability.Networking.Requests.AR.DeliveryOrder.InsertDeliveryLineUploadLogRequest)
  })
_sym_db.RegisterMessage(InsertDeliveryLineUploadLogRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
